nodes:
  - type: read_csv
    description: download
    path: https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv

  - type: rename_columns
    columns:
      species: y

  - type: filter_columns
    columns:
      - y
      - petal_length
      - petal_width
      - sepal_length
      - sepal_width

  - type: drop_columns
    columns:
      - petal_length

  - type: groupby
    by: y
    agg: mean

  - type: head

  - type: to_csv
    path: data/interim/iris_preprocessed.csv
